# On every push this script is executed
on: push
name: Build and deploy GH Pages
# Ensure that this action can write to the gh-pages branch
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v4
      - uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Since we are publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
